=pod

=head1 NAME

AVM-Fritz-Box - Perl interface to AVM's FRITZ!Box

=head1 MODULES

=over 4

=item AVM::Fritz::Box::Session

Provides an interface to the session management of the FRITZ!Box.

=back

=head1 COMPATIBILITY

This module was tested on following FRITZ!Box models and firmware versions:

=over 4

=item FRITZ!Box 7170, Firmware v29.04.87

=back

=cut

